# Site settings
title: xt
email: your-email@domain.com
name: Existential Techie
description: > # this means to ignore newlines until "baseurl:"
  My wanderings and ramblings in tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cognitiaclaeves.github.io" # the base hostname & protocol for your site
twitter_username: cognitiaclaeves
github_username:  cognitiaclaeves

permalink: pretty

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 10
exclude: [process-hacks.sh, post-process-hacks.sh, embed-theme-switch-URLs.py, todo.txt, .git, .gitignore ]
disqusid: data-disqus-identifier

