# Site settings
title: xt
email: your-email@domain.com
name: Existential Techie
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cognitiaclaeves.github.io" # the base hostname & protocol for your site
twitter_username: jekyll
github_username:  cognitiaclaeves

permalink: pretty

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 10
exclude: [docker-compose.yml, run-jekyll.sh]
disqusid: data-disqus-identifier

