# Site settings
title: xt
email: your-email@domain.com
name: Zen Techie
description: > # this means to ignore newlines until "baseurl:"
  Linux, Containers ( Docker ), Orchestration ( Kubernetes ), DevOps (.*) -- Oh My!  
  And other wanderings and ramblings.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://cognitiaclaeves.github.io" # the base hostname & protocol for your site
twitter_username: cognitiaclaeves
github_username:  cognitiaclaeves

# permalink: pretty
permalink: ':categories/blog/:title'

# Build settings
markdown: kramdown
highlighter: pygments
paginate: 10
exclude: [process-hacks.sh, post-process-hacks.sh, embed-theme-switch-URLs.py, todo.txt, .git, .gitignore, source-files ]
disqusid: data-disqus-identifier

